### ISSUE TITLE
PWA is Not Working With Full Functionality

### ISSUE THREAD

**Issue by noscreator** [kumardeo/blogger-pwa#1]
## Issue Description
When I visited the Plus-Ui website and attempted to install the Progressive Web App (PWA), I encountered several Issue 

### PWA Installation Dialog
*Screenshot not required because you know after installation show a app check virus or Malver dealog popup*
The PWA installation process does not display the expected installation dialog. Users should see a confirmation dialog upon installation, which is currently missing.

### Missing Home Page
*Screenshot here you can see home page not Working*
<img src="https://github.com/kumardeo/blogger-pwa/assets/112468782/c39ea369-142b-4ab6-b91a-899c40d691ab" width="400"/>
Upon successful installation, after open app does not display home page. A fully functional PWA should provide users with access to the entire website's content.
But office.html, icon are working show check fallback function and check path

### Limited App Information
*Screenshot check our image and see bug*

<img src="https://github.com/kumardeo/blogger-pwa/assets/112468782/59f8159c-8505-4011-8cdd-a336ee6f3b8d" width="200"/>
<img src="https://github.com/kumardeo/blogger-pwa/assets/112468782/9043df08-d8e7-443c-8b3e-dd10c1b580d6" width="200"/>

When checking the app information,it's showing only the home screen icon is displayed. A typical PWA should offer additional information like site settings, sharing options, and the ability to uninstall the app.

## Request
We kindly request that these issues be investigated and resolved to ensure that the Plus-Ui PWA functions as expected, providing a complete and user-friendly experience.

Your attention to these matters is greatly appreciated.
@noscreator, @kumardeo, @fineshop 
Thank you.

**Comment by fineshop** [comment]
Looks like you are installing the cached app.
Please clear the site data and reinstall the app.
Here is how it should behave like:

![app_info_dialog.png](https://github.com/kumardeo/blogger-pwa/assets/97987158/7f00502b-7ef4-4dbf-a2ba-0756331248bb)

![app_home.png](https://github.com/kumardeo/blogger-pwa/assets/97987158/f01ad693-a928-433c-ad2d-f9e886cee3bb)

**Comment by noscreator** [comment]
Ohh! Sorry Not Cleared Cookies to I got this Bugs..
Now it's Working Properly if Any found then I create a issues

**Comment by noscreator** [comment]
I have one more question! Can We Mack without CLI And Deploy Manual

**Comment by fineshop** [comment]
No, as we are deploying Cloudflare workers using Wrangler CLI as it provides support for ES Modules and makes it easier to bind KV store, environment variables, etc.

**Comment by kumardeo** [comment]
> I have one more question! Can We Mack without CLI And Deploy Manual

Now, it is possible!
