### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by TGXNews** [kumardeo/blogger-pwa#7]
I have tried it on the site tgxnews.com using the Cloudflare method and connecting to OneSignal, but it didn't work. In the Chrome inspect details, there are the following errors:

GET https://www.tgxnews.com/app/pwa.js net::ERR_ABORTED 404 (Not Found)
GET https://www.tgxnews.com/app/manifest.json 404 (Not Found)

**Comment by kumardeo** [comment]
Male sure Proxy is enabled for the CNAME record pointing to your blog in Cloudflare Dashboard.
Also make sure you have correctly routed the workers.

**Comment by kumardeo** [comment]
Closing this issue, since I can see it is working as expected now.
